### ISSUE TITLE
SVG animation on intro component

### ISSUE THREAD

**Issue by armandopbringas** [ciudades-dev/ciudades.dev#7]
# SVG animation on intro component

### Task description

- At intro component Ciudades SVG logo should translate on x axis on scrolling.

### Defined

- The SVG is placed using flexbox.

### TODO

- [ ] Change the implementation from flexbox to CSS position and implement Motion over it
- [ ] Translate the SVG on X axis on scroll
- [ ] Define the breakpoint for translate start and translate end

### QA

- [ ] Translation motion works on mobile, desktop, tablet and > 4K 
- [ ] When scrolling up, the logo will return visible

**Comment by diegoaguilar** [comment]
👍🏼  I've just edited to a more simplified version

**Comment by diegoaguilar** [comment]
https://www.framer.com/api/motion/motionvalue/#useviewportscroll
